<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="THAMU" failures="2" tests="9" name="RetryMultipleFiledTestCases" time="0.116" errors="0" timestamp="2023-06-19T13:41:02 IST">
  <testcase classname="RetryLogic.TestRetry" name="Test1" time="0.014">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.TestRetry" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.TestRetry" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.TestRetry" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogic.TestRetry.Test1(TestRetry.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.TestRetry" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.TestRetry" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.TestRetry" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.TestRetry" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogic.TestRetry.Test2(TestRetry.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.TestRetry" name="Test3" time="0.002"/>
</testsuite> <!-- RetryMultipleFiledTestCases -->
